# Site settings
title: DFIR.CAT
description: Digital Forensics and Incident Response
baseurl: "" # Set to your project's subpath, if necessary (e.g., "/my-website")
url: "https://dfir.cat" # The base URL for your site

# Build settings
markdown: kramdown
theme: minima # You can change this to a different theme or specify your own
gems:
  - jekyll-seo-tag

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Permalinks
permalink: pretty # Use pretty URLs (e.g., /my-page/ instead of /my-page.html)

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .git

# Pagination
paginate: 5 # Number of posts per page

# Date format
date_format: "%Y-%m-%d"

# Custom collections
collections:
  my_collection:
    output: true
    permalink: /my_collection/:title

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
# SEO settings
title_separator: "-"
title_prefix: "DFIR.CAT"
